version: '3'

services:
  mysql:
    container_name: db2
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=anypass # $DB_PASSWORD_2
      - MYSQL_DATABASE=realtimechatdb # $DB_NAME
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  app:
    profiles:
      - in_docker
    container_name: livechat
    build: .
    environment:
      - APP_PORT=80
      - DB_HOST=db2
      - DB_USER_NAME=root
      - DB_PASSWORD=anypass # $DB_PASSWORD_2
      - DB_NAME=realtimechatdb # $DB_NAME
    ports:
      - "5000:80"
    healthcheck:
      test: ["CMD", "curl", "http://localhost"]
      timeout: 20s
      retries: 5
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data:

