name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    
    - name: Set image version (tag)
      id: image_version
      run: echo "gitsha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/m-alsuleibi/express-docker:${{ steps.image_version.outputs.gitsha }}
    - name: Publish docker image
      run: docker push ghcr.io/m-alsuleibi/express-docker:${{ steps.image_version.outputs.gitsha }}
    - name: configure docker host
      uses: khaledez/configure-docker-host@v1 #can be always used 
      with:
        host: 13.40.45.17
        user: github
        ssh-private-key: ${{ secrets.DEPLOYMENT_KEY }}
    - name: deploy
      run: docker compose -f docker-compose-prod.yml up -d
      env: 
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}  
    
    - name: print logs 
      if: always()
      run: docker compose logs 